// Builds a self-hosted Font Awesome subset containing only the icons this
// site actually uses (~57 of Font Awesome's several thousand), instead of
// pulling the full ~267KB solid+brands webfonts from a CDN on every page.
//
// Prerequisites (not part of the normal `npm run build` — this only needs
// re-running when a *new* icon is added to a page, which is rare):
//   1. `npm install --no-save @fortawesome/fontawesome-free@6.5.0`
//   2. `pip install fonttools` (provides `python3 -m fontTools.subset`)
//
// Run with: node scripts/subset-icons.mjs
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FA_PKG = path.join(ROOT, 'node_modules/@fortawesome/fontawesome-free');
const OUT_FONT_DIR = path.join(ROOT, 'assets/fonts/icons');
const OUT_CSS = path.join(ROOT, 'src/css/icons.css');
const EXCLUDE_DIRS = new Set(['node_modules', '.git', '.claude', '_source', 'scripts', 'assets']);

async function findHtmlFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      files.push(...(await findHtmlFiles(path.join(dir, entry.name))));
    } else if (entry.name.endsWith('.html')) {
      files.push(path.join(dir, entry.name));
    }
  }
  return files;
}

function extractIconNames(text, family) {
  // Matches both the long form ("fa-solid fa-house") and the legacy short
  // form ("fas fa-house" / "fab fa-linkedin-in").
  const patterns = {
    solid: /\b(?:fa-solid|fas)\s+fa-([a-z0-9-]+)/g,
    brands: /\b(?:fa-brands|fab)\s+fa-([a-z0-9-]+)/g,
  };
  const re = patterns[family];
  const names = new Set();
  let m;
  while ((m = re.exec(text))) names.add(m[1]);
  return names;
}

async function main() {
  const htmlFiles = await findHtmlFiles(ROOT);
  const solidNames = new Set();
  const brandsNames = new Set();
  for (const f of htmlFiles) {
    const text = await readFile(f, 'utf8');
    extractIconNames(text, 'solid').forEach((n) => solidNames.add(n));
    extractIconNames(text, 'brands').forEach((n) => brandsNames.add(n));
  }
  // Icons only ever referenced dynamically from JS (theme toggle swaps
  // moon <-> sun) — grep can't see these in the HTML, so list them by hand.
  ['sun'].forEach((n) => solidNames.add(n));

  console.log(`Found ${solidNames.size} solid + ${brandsNames.size} brand icons in use.`);

  const metadata = JSON.parse(
    await readFile(path.join(FA_PKG, 'metadata/icon-families.json'), 'utf8')
  );

  function resolve(names, family) {
    const map = {};
    for (const name of names) {
      const entry = metadata[name];
      if (!entry || !entry.svgs?.classic?.[family]) {
        throw new Error(`Icon "${name}" not found in Font Awesome ${family} family — check the class name.`);
      }
      map[name] = entry.unicode;
    }
    return map;
  }
  const solidMap = resolve(solidNames, 'solid');
  const brandsMap = resolve(brandsNames, 'brands');

  await mkdir(OUT_FONT_DIR, { recursive: true });

  function subsetFont(srcFile, destFile, codepoints) {
    const unicodes = codepoints.map((cp) => `U+${cp}`).join(',');
    execFileSync('python3', [
      '-m', 'fontTools.subset',
      path.join(FA_PKG, 'webfonts', srcFile),
      `--output-file=${path.join(OUT_FONT_DIR, destFile)}`,
      `--unicodes=${unicodes}`,
      '--flavor=woff2',
      '--layout-features=*',
      '--no-hinting',
      '--desubroutinize',
    ], { stdio: 'inherit' });
  }
  subsetFont('fa-solid-900.woff2', 'fa-solid-900.woff2', Object.values(solidMap));
  subsetFont('fa-brands-400.woff2', 'fa-brands-400.woff2', Object.values(brandsMap));

  const iconRules = [
    ...Object.entries(solidMap).map(([name, cp]) => `.fa-${name}::before { content: "\\${cp}"; }`),
    ...Object.entries(brandsMap).map(([name, cp]) => `.fa-${name}::before { content: "\\${cp}"; }`),
  ].sort().join('\n');

  const css = `/* ==========================================================================
   Self-hosted Font Awesome subset — generated by scripts/subset-icons.mjs.
   Only the ~${solidMap && Object.keys(solidMap).length + Object.keys(brandsMap).length} icons this site actually uses, instead of the
   full ~267KB solid+brands webfonts from the cdnjs CDN. Re-run the script
   (see its header comment) after adding a new fa-* icon to a page.
   ========================================================================== */
@font-face {
  font-family: 'Font Awesome 6 Free';
  font-style: normal;
  font-weight: 900;
  font-display: block;
  src: url('../fonts/icons/fa-solid-900.woff2') format('woff2');
}
@font-face {
  font-family: 'Font Awesome 6 Brands';
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url('../fonts/icons/fa-brands-400.woff2') format('woff2');
}

.fa-solid, .fas, .fa-brands, .fab {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  display: inline-block;
  font-style: normal;
  font-variant: normal;
  line-height: 1;
  text-rendering: auto;
}
.fa-solid, .fas { font-family: 'Font Awesome 6 Free'; font-weight: 900; }
.fa-brands, .fab { font-family: 'Font Awesome 6 Brands'; font-weight: 400; }

${iconRules}
`;

  await writeFile(OUT_CSS, css, 'utf8');
  console.log(`Wrote ${OUT_CSS} and subset fonts to ${OUT_FONT_DIR}`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
